epochs: 100
batch_size: 128
lr: 2e-3
layer_decay: 0.65
opt: adamw
sched: cosine
weight_decay: 0.05
warmup_epochs: 5
warmup_lr: 1e-4
min_lr: 1e-6
smoothing: 0.1
aa: rand-m9-mstd0.5-inc1
mixup: 0.8
cutmix: 1.0
color_jitter: 0.0
reprob: 0.25
drop_path: 0.1