model: meta-baseline
model_args: 
    encoder: resnet18
    encoder_args: {}
load_encoder: ./save/pretrain-multi/epoch-last.pth

freeze_bn: True

n_train: 1000
n_eval: 400

max_epoch: 5
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 1.e-4}

save_epoch: 1
